---
title: "Introdução"
output:
  word_document: default
  html_document: default
---

As comunidades florestais apresentam um complexo ecossistema com diferentes inter-relações funcionais, em diferentes estágios de sucessão que crescem, reproduzem-se e morrem [@Withmore1989, @Schorn2009]. Uma forma de reduzir esta complexidade é agrupar as espécies a partir de suas similaridades. Estas similaridades podem estar associadas às características morfológicas, às estratégias de vida, ou mesmo, às estratégias de dispersão. Essas semelhanças podem ser utilizadas para agrupar as espécies em grupos ecológicos [@Denslow1987, @Swaine1987, @Clark1992, @Campanello2007, @Dealmeida2016].

A exploração madeireira sustentável é executada através do plano de manejo florestal. Este deve estar embasado em princípios como floresta regulada e equilibrada, para recomendar a intensidade de exploração, e as espécies a serem manejadas. A sustentabilidade do manejo está associado à capacidade da floresta em repor o que foi explorado [@Oliveira2020]. 

A capacidade de recuperação está intimamente relacionada ao crescimento das árvores. Esse crescimento é consequência das atividades meristemáticas que resultam na criação de novas células em duas direções fundamentais: no sentido apical, que pode ser medido na mudança da altura da árvore; e no sentido lateral, que pode ser medido no diâmetro da árvore. Mudanças nas dimensões, tem como consequência o crescimento volumétrico da árvore, resultando em acúmulo de madeira. Tanto fatores genéticos quanto ambientais influenciam o desenvolvimento de um indivíduo, seja na forma e seja no tamanho [@SetteJr2010, @Canhoto2018].

Compreender o crescimento das espécies é portanto fundamental. Em geral, os parâmetros de corte para a exploração florestal são definidos de modo genérico. Valores de crescimento e distribuição dos indivíduos são únicos para toda a floresta, desconsiderando a diversidade de espécies arbóreas. Considerar os agrupamentos ecológicos ajuda a compreender a dinâmica e a estrutura da floresta, permitindo a incorporação de instrumentos reguladores no manejo florestal. Assim, espera-se que as atividades exploratórias, orientadas por tais instrumentos, não modifiquem a composição e estrutura da comunidade [@Oliver1996].

Desconsiderar as diferenças entre as espécies leva a taxas de explorações sub-ótimas, compromento a sustentabilidade em nível de espécie [@Conde2022]. Desta forma, o presente trabalho pretende avaliar os diferentes grupos ecológicos a partir da distribuição diamétrica, do incremento diamétrico anual e do tempo de passagem. Espera-se fornecer subsídios para a definição de critérios de corte mais adequados e que promovam um manejo florestal sustentável de floretas tropicais.

