---
title: "Material e Métodos"
output: html_document
---

```{r packages2}
require(tidyverse)
require(magrittr)
require(reshape2)
require(ggplot2)
require(V.PhyloMaker)
require(phytools)
require(knitr)
```
Sobre os inventários... processamento e padronização...

#```{r mergeInventarios, child="02merge.Rmd"}
#```

Remove não árvores e remove indivíduos sem diâmetro... falar da necessidade dos dados pareados....


```{r cleanInv}
invMerged = read.csv("dados/10_invPaisagensMerged.csv")
invMerged = invMerged %>%
  filter(type == "O" | is.na(type)) %>%
  drop_na(DBH)
```

Determinar o número de parcelas em cada sítio...

```{r}
parcelasArea = invMerged %>%
  group_by(area, plot, subplot, year) %>%
  summarise(obs = n()) %>%
  group_by(area, year) %>%
  summarise(nplots = n()) %>%
  group_by(area) %>%
  summarise(nplots = mean(nplots))
```

Explain growth...

$$growth = \frac{d2 - d1}{t2 - t1}$$

Explain relative growth...

$$RGrowth = \frac{growth}{d1}$$
Ecological groups....

```{r}
grupoEco = read.csv('auxiliar/grupoEcologico.csv')
eco = grupoEco %>% group_by(GrupoEco) %>% summarise(Species = n())
kable(eco, col.names = c('Ecological groups', 'Number of species'), caption = 'Number of species associated to each ecological group.')
```

Incremento por grupo ecológico...

```{r}
incEco = invMerged %>%
  drop_na(GrupoEco) %>%
  group_by(area, plot, subplot, tree, scientific.name, GrupoEco) %>%
  summarise(med = n(),
            cc = min(cc), 
            minDBH = min(DBH), 
            maxDBH = max(DBH), 
            inc = max(DBH) - min(DBH), 
            intervMed = max(year) - min(year), 
            incAnual = ifelse(inc == 0, 0, inc / intervMed)) %>%
  filter(med > 1)
  
```


Commercial interest...

```{r}
commercialSpecies = read.csv('auxiliar/comercial.csv')
commercial = commercialSpecies %>% group_by(comercial) %>% summarise(Species = n())
kable(commercial, col.names = c('Commecial interest', 'Number of species'), caption = 'Number of species associated to commercial intesrest.')
```

```{r}
incComercial = invMerged %>%
  drop_na(comercial) %>%
  group_by(area, plot, subplot, tree, scientific.name, comercial) %>%
  summarise(med = n(),
            cc = min(cc), 
            minDBH = min(DBH), 
            maxDBH = max(DBH), 
            inc = max(DBH) - min(DBH), 
            intervMed = max(year) - min(year), 
            incAnual = ifelse(inc == 0, 0, inc / intervMed)) %>%
  filter(med > 1)
```

Compute residence time to reach 50 cm...

```{r}

```



