---
title: "Resultados"
output: html_document
---

```{r packages3}
require(tidyverse)
require(magrittr)
require(plotly)
require(reshape2)
require(ggplot2)
require(V.PhyloMaker)
require(phytools)
```

```{r echo=FALSE}
inv.paisagens = read.csv("dados/10_invPaisagensMerged.csv")
inv.paisagens = inv.paisagens %>%
  filter(type == "O" | is.na(type)) %>%
  filter(scientific.name != 'NI') %>%
  drop_na(DBH)

parcelasArea = inv.paisagens %>%
  group_by(area, plot, subplot, year) %>%
  summarise(obs = n()) %>%
  group_by(area, year) %>%
  summarise(nplots = n()) %>%
  group_by(area) %>%
  summarise(nplots = mean(nplots))
```

Resumo de todo o conjunto de dados....

```{r hipsometria}
ggplot(inv.paisagens, aes(DBH, Htot)) +                                
  geom_point(alpha = 0.1) + 
  theme_bw() + theme(panel.grid.major = element_blank(),
                     panel.grid.minor = element_blank(),
                     panel.background = element_blank(),
                     axis.line = element_line(colour = "black"))
```

Modelar de forma bayesiana...

```
incrementosModel = glm(data = incremento, incAnual ~ minDBH, family=Gamma(link="log"))
summary(incrementosModel)
```

## Grupo ecológicos

Espécies por grupo ecológico...

```{r}
arvHaEspecie = inv.paisagens %>%
  drop_na(GrupoEco) %>%
  filter(DBH >= 10) %>%
  group_by(area, plot, subplot, year, GrupoEco) %>% 
  summarise(ntree = sum(eqTree)) %>%
  drop_na(ntree) %>%
  group_by(area, plot, subplot, GrupoEco) %>%
  summarise(ntree = mean(ntree)) %>%
  group_by(area, GrupoEco) %>%
  summarise(ntree = sum(ntree)) %>%
  left_join(parcelasArea) %>%
  mutate(arvha = ntree / nplots) %>%
  group_by(GrupoEco) %>%
  summarise(arvha = mean(arvha))

arvHaEspecie
```

### Pioneiras

```{r}
grupo = "Pioneer"

grupoEcologico = inv.paisagens %>%
  filter(GrupoEco == grupo)
```

```{r}
filogenia = grupoEcologico %>%                                                    # filogenia das spécies estudadas
  group_by(scientific.name, genera.name, family.name) %>%
  summarise(n = n()) %>%
  drop_na(family.name) %>%
  filter(!is.na(family.name)) %>%
  filter(family.name != 'NI')
```

```{r cache=TRUE}
phy = phylo.maker(filogenia[,1:3])
tree = phy$scenario.3
plotTree(tree, type='fan', fsize=0.5, lwd=1, ftype='i')
```


```{r}
#for(i in unique(inv.paisagens.filtered$GrupoEco)){
  numeroArvores = inv.paisagens %>%
    filter(GrupoEco == grupo) %>%
    filter(DBH >= 10) %>%
    group_by(area, plot, subplot, year, cc) %>% 
    summarise(ntree = sum(eqTree))  %>%
    drop_na(ntree) %>%
    group_by(area, cc) %>%
    summarise(narv = sum(ntree)) %>%
    left_join(parcelasArea) %>%
    mutate(arvha = narv / nplots) %>%
    group_by(cc) %>%
    summarise(arvha = mean(arvha))
  
  ggplot(numeroArvores, aes(cc, arvha)) + geom_col() +
    xlab('Diameter distribution') + ylab('Trees per hectare') +
    ggtitle(paste0(grupo)) + 
    theme_bw() + theme(panel.grid.major = element_blank(),
                       panel.grid.minor = element_blank(),
                       panel.background = element_blank(),
                       axis.line = element_line(colour = "black"))
#}
```

### Demandantes de luz

```{r}
grupo = "Light-demanding" 

grupoEcologico = inv.paisagens %>%
  filter(GrupoEco == grupo)
```

```{r}
filogenia = grupoEcologico %>%                                                    # filogenia das spécies estudadas
  group_by(scientific.name, genera.name, family.name) %>%
  summarise(n = n()) %>%
  drop_na(family.name) %>%
  filter(!is.na(family.name)) %>%
  filter(family.name != 'NI')
```

```{r cache=TRUE}
phy = phylo.maker(filogenia[,1:3])
tree = phy$scenario.3
plotTree(tree, type='fan', fsize=0.5, lwd=1, ftype='i')
```

```{r}
#for(i in unique(inv.paisagens.filtered$GrupoEco)){
  numeroArvores = inv.paisagens %>%
    filter(GrupoEco == grupo) %>%
    filter(DBH >= 10) %>%
    group_by(area, plot, subplot, year, cc) %>% 
    summarise(ntree = sum(eqTree))  %>%
    drop_na(ntree) %>%
    group_by(area, cc) %>%
    summarise(narv = sum(ntree)) %>%
    left_join(parcelasArea) %>%
    mutate(arvha = narv / nplots) %>%
    group_by(cc) %>%
    summarise(arvha = mean(arvha))
  
  ggplot(numeroArvores, aes(cc, arvha)) + geom_col() +
    xlab('Diameter distribution') + ylab('Trees per hectare') +
    ggtitle(paste0(grupo)) + 
    theme_bw() + theme(panel.grid.major = element_blank(),
                       panel.grid.minor = element_blank(),
                       panel.background = element_blank(),
                       axis.line = element_line(colour = "black"))
#}
```

### Intermediárias

```{r}
grupo = "Intermediate"

grupoEcologico = inv.paisagens %>%
  filter(GrupoEco == grupo)
```

```{r}
filogenia = grupoEcologico %>%                                                    # filogenia das spécies estudadas
  group_by(scientific.name, genera.name, family.name) %>%
  summarise(n = n()) %>%
  drop_na(family.name) %>%
  filter(!is.na(family.name)) %>%
  filter(family.name != 'NI')
```

```{r cache=TRUE}
phy = phylo.maker(filogenia[,1:3])
tree = phy$scenario.3
plotTree(tree, type='fan', fsize=0.5, lwd=1, ftype='i')
```

```{r}
#for(i in unique(inv.paisagens.filtered$GrupoEco)){
  numeroArvores = inv.paisagens %>%
    filter(GrupoEco == grupo) %>%
    filter(DBH >= 10) %>%
    group_by(area, plot, subplot, year, cc) %>% 
    summarise(ntree = sum(eqTree))  %>%
    drop_na(ntree) %>%
    group_by(area, cc) %>%
    summarise(narv = sum(ntree)) %>%
    left_join(parcelasArea) %>%
    mutate(arvha = narv / nplots) %>%
    group_by(cc) %>%
    summarise(arvha = mean(arvha))
  
  ggplot(numeroArvores, aes(cc, arvha)) + geom_col() +
    xlab('Diameter distribution') + ylab('Trees per hectare') +
    ggtitle(paste0(grupo)) + 
    theme_bw() + theme(panel.grid.major = element_blank(),
                       panel.grid.minor = element_blank(),
                       panel.background = element_blank(),
                       axis.line = element_line(colour = "black"))
#}
```

### Shade-tolerant

```{r}
grupo = "Shade-tolerant"

grupoEcologico = inv.paisagens %>%
  filter(GrupoEco == grupo)
```

```{r}
filogenia = grupoEcologico %>%                                                    # filogenia das spécies estudadas
  group_by(scientific.name, genera.name, family.name) %>%
  summarise(n = n()) %>%
  drop_na(family.name) %>%
  filter(!is.na(family.name)) %>%
  filter(family.name != 'NI')
```

```{r cache=TRUE}
phy = phylo.maker(filogenia[,1:3])
tree = phy$scenario.3
plotTree(tree, type='fan', fsize=0.5, lwd=1, ftype='i')
```

```{r}
#for(i in unique(inv.paisagens.filtered$GrupoEco)){
  numeroArvores = inv.paisagens %>%
    filter(GrupoEco == grupo) %>%
    filter(DBH >= 10) %>%
    group_by(area, plot, subplot, year, cc) %>% 
    summarise(ntree = sum(eqTree))  %>%
    drop_na(ntree) %>%
    group_by(area, cc) %>%
    summarise(narv = sum(ntree)) %>%
    left_join(parcelasArea) %>%
    mutate(arvha = narv / nplots) %>%
    group_by(cc) %>%
    summarise(arvha = mean(arvha))
  
  ggplot(numeroArvores, aes(cc, arvha)) + geom_col() +
    xlab('Diameter distribution') + ylab('Trees per hectare') +
    ggtitle(paste0(grupo)) + 
    theme_bw() + theme(panel.grid.major = element_blank(),
                       panel.grid.minor = element_blank(),
                       panel.background = element_blank(),
                       axis.line = element_line(colour = "black"))
#}
```

### Emergente demandante de luz

```{r}
grupo = "Emergent"

grupoEcologico = inv.paisagens %>%
  filter(GrupoEco == grupo)
```

```{r}
filogenia = grupoEcologico %>%                                                    # filogenia das spécies estudadas
  group_by(scientific.name, genera.name, family.name) %>%
  summarise(n = n()) %>%
  drop_na(family.name) %>%
  filter(!is.na(family.name)) %>%
  filter(family.name != 'NI')
```

```{r cache=TRUE}
phy = phylo.maker(filogenia[,1:3])
tree = phy$scenario.3
plotTree(tree, type='fan', fsize=0.5, lwd=1, ftype='i')
```

```{r}
#for(i in unique(inv.paisagens.filtered$GrupoEco)){
  numeroArvores = inv.paisagens %>%
    filter(GrupoEco == grupo) %>%
    filter(DBH >= 10) %>%
    group_by(area, plot, subplot, year, cc) %>% 
    summarise(ntree = sum(eqTree))  %>%
    drop_na(ntree) %>%
    group_by(area, cc) %>%
    summarise(narv = sum(ntree)) %>%
    left_join(parcelasArea) %>%
    mutate(arvha = narv / nplots) %>%
    group_by(cc) %>%
    summarise(arvha = mean(arvha))
  
  ggplot(numeroArvores, aes(cc, arvha)) + geom_col() +
    xlab('Diameter distribution') + ylab('Trees per hectare') +
    ggtitle(paste0(grupo)) + 
    theme_bw() + theme(panel.grid.major = element_blank(),
                       panel.grid.minor = element_blank(),
                       panel.background = element_blank(),
                       axis.line = element_line(colour = "black"))
#}
```

### Incremento por grupo ecológico

```{r}
incremento = inv.paisagens %>%
  drop_na(GrupoEco) %>%
  group_by(area, plot, subplot, tree, scientific.name, GrupoEco) %>%
  summarise(med = n(),
            cc = min(cc), 
            minDBH = min(DBH), 
            maxDBH = max(DBH), 
            inc = max(DBH) - min(DBH), 
            intervMed = max(year) - min(year), 
            incAnual = ifelse(inc == 0, 0, inc / intervMed)) %>%
  filter(med > 1)
  
```

```{r}
incrementoGrupo = incremento %>%
  group_by(GrupoEco) %>%
  summarise(incDesv = IQR(incAnual, na.rm = TRUE), 
            incAnual = median(incAnual), 
            tp = 50 / incAnual)

incrementoGrupo
```

Emtrar com Bayesiana??

```
incremento$GrupoEco <- factor(incremento$GrupoEco, 
                              levels=c("OUTROS","Pioneer","Light-demanding", 
                                       "Intermediate", "Shade-tolerant", "Emergent"))
grupoEcoModel = glm(data = incremento, incAnual ~ minDBH + GrupoEco, family=Gamma(link="log"))
summary(grupoEcoModel)
```

## Comercial

```{r}
arvHaEspecie = inv.paisagens %>%
  drop_na(comercial) %>%
  filter(DBH >= 10) %>%
  group_by(area, plot, subplot, year, comercial) %>% 
  summarise(ntree = sum(eqTree)) %>%
  drop_na(ntree) %>%
  group_by(area, plot, subplot, comercial) %>%
  summarise(ntree = mean(ntree)) %>%
  group_by(area, comercial) %>%
  summarise(ntree = sum(ntree)) %>%
  left_join(parcelasArea) %>%
  mutate(arvha = ntree / nplots) %>%
  group_by(comercial) %>%
  summarise(arvha = mean(arvha))

arvHaEspecie
```

```{r}
grupo = 1

comercial = inv.paisagens %>%
  filter(comercial == grupo)
```

```{r}
filogenia = comercial %>%                                                    # filogenia das spécies estudadas
  group_by(scientific.name, genera.name, family.name) %>%
  summarise(n = n()) %>%
  drop_na(family.name) %>%
  filter(!is.na(family.name)) %>%
  filter(family.name != 'NI')
```

```{r cache=TRUE}
phy = phylo.maker(filogenia[,1:3])
tree = phy$scenario.3
plotTree(tree, type='fan', fsize=0.5, lwd=1, ftype='i')
```

```{r}
#for(i in c(0, 1)){
  numeroArvores = inv.paisagens %>%
    filter(comercial == 1) %>%
    filter(DBH >= 10) %>%
    group_by(area, plot, subplot, year, cc) %>% 
    summarise(ntree = sum(eqTree))  %>%
    drop_na(ntree) %>%
    group_by(area, cc) %>%
    summarise(narv = sum(ntree)) %>%
    left_join(parcelasArea) %>%
    mutate(arvha = narv / nplots) %>%
    group_by(cc) %>%
    summarise(arvha = mean(arvha))
  
  ggplot(numeroArvores, aes(cc, arvha)) + geom_col() +
    xlab('Diameter distribution') + ylab('Trees per hectare') +
    ggtitle('commercial') + 
    theme_bw() + theme(panel.grid.major = element_blank(),
                       panel.grid.minor = element_blank(),
                       panel.background = element_blank(),
                       axis.line = element_line(colour = "black"))
#}
```

```{r}
#for(i in c(0, 1)){
  numeroArvores = inv.paisagens %>%
    filter(comercial == 0) %>%
    filter(DBH >= 10) %>%
    group_by(area, plot, subplot, year, cc) %>% 
    summarise(ntree = sum(eqTree))  %>%
    drop_na(ntree) %>%
    group_by(area, cc) %>%
    summarise(narv = sum(ntree)) %>%
    left_join(parcelasArea) %>%
    mutate(arvha = narv / nplots) %>%
    group_by(cc) %>%
    summarise(arvha = mean(arvha))
  
  ggplot(numeroArvores, aes(cc, arvha)) + geom_col() +
    xlab('Diameter distribution') + ylab('Trees per hectare') +
    ggtitle('non-commercial') + 
    theme_bw() + theme(panel.grid.major = element_blank(),
                       panel.grid.minor = element_blank(),
                       panel.background = element_blank(),
                       axis.line = element_line(colour = "black"))
#}
```

### Incremento por grupo de interesse comercial

```{r}
incremento = inv.paisagens %>%
  drop_na(comercial) %>%
  group_by(area, plot, subplot, tree, scientific.name, comercial) %>%
  summarise(med = n(),
            cc = min(cc), 
            minDBH = min(DBH), 
            maxDBH = max(DBH), 
            inc = max(DBH) - min(DBH), 
            intervMed = max(year) - min(year), 
            incAnual = ifelse(inc == 0, 0, inc / intervMed)) %>%
  filter(med > 1)
```

```{r}
incrementoGrupo = incremento %>%
  group_by(comercial) %>%
  summarise(incDesv = IQR(incAnual, na.rm = TRUE), 
            incAnual = median(incAnual), 
            tp = 50 / incAnual)

incrementoGrupo
```

Modelar por bayesiana...

```
comercialModel = glm(data = incremento, incAnual ~ minDBH + comercial, family=Gamma(link="log"))
summary(comercialModel)
```




