---
title: "05apendice.Rmd"
output: html_document
---

## Espécies

```{r}
filogenia = inv.paisagens.filtered %>%                                          # filogenia das spécies estudadas
  filter(comercial == 1) %>%
  group_by(scientific.name, genera.name, family.name) %>%
  summarise(n = n()) %>%
  drop_na(family.name) %>%
  filter(!is.na(family.name)) %>%
  filter(family.name != 'NI')
```

```{r}
phy = phylo.maker(filogenia[,1:3])
#write.tree(phy$scenario.3, "Figure.1.tre")
tree = phy$scenario.3
plotTree(tree, type='fan', fsize=0.5, lwd=3, ftype='i')

```

```{r}
speciesList = inv.paisagens.filtered %>%                                        # Lista das espécies com maior número de árvores
  filter(comercial == 1) %>%                                                    # filtra espécies comerciais
  group_by(scientific.name) %>%
  summarise(ntree = n()) %>%
  filter(ntree > 60) %>%
  select(scientific.name)
```

```{r}
arvHaEspecie = inv.paisagens.filtered %>%
  filter(DBH >= 10) %>%
  group_by(area, plot, subplot, year, scientific.name) %>% 
  summarise(ntree = sum(eqTree)) %>%
  drop_na(ntree) %>%
  group_by(area, plot, subplot, scientific.name) %>%
  summarise(ntree = mean(ntree)) %>%
  group_by(area, scientific.name) %>%
  summarise(ntree = sum(ntree)) %>%
  left_join(parcelasArea) %>%
  mutate(arvha = ntree / nplots) %>%
  group_by(scientific.name) %>%
  summarise(arvha = mean(arvha)) %>%
  filter(scientific.name %in% speciesList$scientific.name)
```


```{r eval=FALSE}
for(i in speciesList$scientific.name){
  numeroArvores = inv.paisagens.filtered %>%
    filter(scientific.name == i) %>%
    filter(DBH >= 10) %>%
    group_by(area, plot, subplot, year, cc) %>% 
    summarise(ntree = sum(eqTree))  %>%
    drop_na(ntree) %>%
    group_by(area, cc) %>%
    summarise(narv = sum(ntree)) %>%
    left_join(parcelasArea) %>%
    mutate(arvha = narv / nplots) %>%
    group_by(cc) %>%
    summarise(arvha = mean(arvha))
    
  ggplot(numeroArvores, aes(cc, arvha)) + geom_col() +
    xlab('Diameter distribution') + ylab('Trees per hectare') +
    ggtitle(paste0(i)) + 
    theme_bw() + theme(panel.grid.major = element_blank(),
                       panel.grid.minor = element_blank(),
                       panel.background = element_blank(),
                       axis.line = element_line(colour = "black"))
}
```


```{r}
incremento = inv.paisagens %>%
  group_by(area, plot, subplot, tree, scientific.name) %>%
  summarise(cc = min(cc), minDBH = min(DBH), maxDBH = max(DBH), 
            inc = max(DBH) - min(DBH), intervMed = max(year) - min(year), 
            incAnual = inc / intervMed) %>%
  filter(inc > 0)
```


```{r}
incrementoSpecies = incremento %>%
  filter(scientific.name %in% speciesList$scientific.name) %>%
  group_by(scientific.name) %>%
  summarise(incAnual = mean(incAnual), tp = 50 / incAnual)
```

```{r}
ggplot(incremento, aes(as.factor(cc), incAnual)) + geom_boxplot() +
  xlab('Diameter class') +
  theme_bw() + theme(panel.grid.major = element_blank(),
                     panel.grid.minor = element_blank(),
                     panel.background = element_blank(),
                     axis.line = element_line(colour = "black"))
```

